# -*- coding: utf-8 -*-
"""Python_example.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JMz9nAq7KKl5cmBX7BjAsgRACviQOIWI
"""

import pandas as pd
import numpy as np

#Adding Basic Python Script  
# Expected grade
grade = 70
# Check the is more than 70 or not
if (grade >= 70):
    print("You have passed")
else:
    print("You have not passed")